<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Section 2 Exploratory Data Analysis | R Basic Course</title>
  <meta name="description" content="Section 2 Exploratory Data Analysis | R Basic Course" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Section 2 Exploratory Data Analysis | R Basic Course" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Section 2 Exploratory Data Analysis | R Basic Course" />
  
  
  

<meta name="author" content="Mardones, Mauricio &amp; Zúñiga, María José." />


<meta name="date" content="2025-02-12" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="user.-intro-to-r-and-basic-features.html"/>
<link rel="next" href="visualization..html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R Basic Course</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About Course_R</a></li>
<li class="chapter" data-level="1" data-path="user.-intro-to-r-and-basic-features.html"><a href="user.-intro-to-r-and-basic-features.html"><i class="fa fa-check"></i><b>1</b> <strong>useR</strong>. Intro to R and basic features</a>
<ul>
<li class="chapter" data-level="1.1" data-path="user.-intro-to-r-and-basic-features.html"><a href="user.-intro-to-r-and-basic-features.html#welcome-r-user"><i class="fa fa-check"></i><b>1.1</b> Welcome R user</a></li>
<li class="chapter" data-level="1.2" data-path="user.-intro-to-r-and-basic-features.html"><a href="user.-intro-to-r-and-basic-features.html#why-learn-r"><i class="fa fa-check"></i><b>1.2</b> ¿Why learn R?</a></li>
<li class="chapter" data-level="1.3" data-path="user.-intro-to-r-and-basic-features.html"><a href="user.-intro-to-r-and-basic-features.html#origin-of-r"><i class="fa fa-check"></i><b>1.3</b> Origin of R</a></li>
<li class="chapter" data-level="1.4" data-path="user.-intro-to-r-and-basic-features.html"><a href="user.-intro-to-r-and-basic-features.html#getting-started"><i class="fa fa-check"></i><b>1.4</b> Getting Started</a></li>
<li class="chapter" data-level="1.5" data-path="user.-intro-to-r-and-basic-features.html"><a href="user.-intro-to-r-and-basic-features.html#basic-data-types"><i class="fa fa-check"></i><b>1.5</b> Basic Data Types</a></li>
<li class="chapter" data-level="1.6" data-path="user.-intro-to-r-and-basic-features.html"><a href="user.-intro-to-r-and-basic-features.html#vectors"><i class="fa fa-check"></i><b>1.6</b> Vectors</a></li>
<li class="chapter" data-level="1.7" data-path="user.-intro-to-r-and-basic-features.html"><a href="user.-intro-to-r-and-basic-features.html#data-frames"><i class="fa fa-check"></i><b>1.7</b> Data Frames</a></li>
<li class="chapter" data-level="1.8" data-path="user.-intro-to-r-and-basic-features.html"><a href="user.-intro-to-r-and-basic-features.html#visualization"><i class="fa fa-check"></i><b>1.8</b> Visualization</a></li>
<li class="chapter" data-level="1.9" data-path="user.-intro-to-r-and-basic-features.html"><a href="user.-intro-to-r-and-basic-features.html#functions"><i class="fa fa-check"></i><b>1.9</b> Functions</a></li>
<li class="chapter" data-level="1.10" data-path="user.-intro-to-r-and-basic-features.html"><a href="user.-intro-to-r-and-basic-features.html#statistical-analysis"><i class="fa fa-check"></i><b>1.10</b> Statistical Analysis</a></li>
<li class="chapter" data-level="1.11" data-path="user.-intro-to-r-and-basic-features.html"><a href="user.-intro-to-r-and-basic-features.html#conclusion"><i class="fa fa-check"></i><b>1.11</b> Conclusion</a></li>
<li class="chapter" data-level="1.12" data-path="user.-intro-to-r-and-basic-features.html"><a href="user.-intro-to-r-and-basic-features.html#sources"><i class="fa fa-check"></i><b>1.12</b> Sources</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html"><i class="fa fa-check"></i><b>2</b> Exploratory Data Analysis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#load-necessary-packages"><i class="fa fa-check"></i><b>2.1</b> Load Necessary Packages</a></li>
<li class="chapter" data-level="2.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#load-and-clean-data"><i class="fa fa-check"></i><b>2.2</b> Load and Clean Data</a></li>
<li class="chapter" data-level="2.3" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#basic-data-overview"><i class="fa fa-check"></i><b>2.3</b> Basic Data Overview</a></li>
<li class="chapter" data-level="2.4" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>2.4</b> Measures of Central Tendency</a></li>
<li class="chapter" data-level="2.5" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#measures-of-spread"><i class="fa fa-check"></i><b>2.5</b> Measures of Spread</a></li>
<li class="chapter" data-level="2.6" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#frequency-tables-for-categorical-data"><i class="fa fa-check"></i><b>2.6</b> Frequency Tables for Categorical Data</a></li>
<li class="chapter" data-level="2.7" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#relationships-between-variables"><i class="fa fa-check"></i><b>2.7</b> Relationships Between Variables</a></li>
<li class="chapter" data-level="2.8" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#outlier-detection"><i class="fa fa-check"></i><b>2.8</b> Outlier Detection</a></li>
<li class="chapter" data-level="2.9" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#comparison-between-groups"><i class="fa fa-check"></i><b>2.9</b> Comparison Between Groups</a></li>
<li class="chapter" data-level="2.10" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#statistical-test-t-test"><i class="fa fa-check"></i><b>2.10</b> Statistical Test: t-Test</a></li>
<li class="chapter" data-level="2.11" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#one-way-anova"><i class="fa fa-check"></i><b>2.11</b> One-Way ANOVA</a></li>
<li class="chapter" data-level="2.12" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#simple-linear-regression"><i class="fa fa-check"></i><b>2.12</b> Simple Linear Regression</a></li>
<li class="chapter" data-level="2.13" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#multiple-regresion"><i class="fa fa-check"></i><b>2.13</b> Multiple Regresion</a></li>
<li class="chapter" data-level="2.14" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#conclusion-1"><i class="fa fa-check"></i><b>2.14</b> Conclusion</a></li>
<li class="chapter" data-level="2.15" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#final-thoughts"><i class="fa fa-check"></i><b>2.15</b> Final Thoughts</a></li>
<li class="chapter" data-level="2.16" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#references"><i class="fa fa-check"></i><b>2.16</b> References</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="visualization..html"><a href="visualization..html"><i class="fa fa-check"></i><b>3</b> Visualization.</a>
<ul>
<li class="chapter" data-level="3.1" data-path="visualization..html"><a href="visualization..html#graphics"><i class="fa fa-check"></i><b>3.1</b> Graphics</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="visualization..html"><a href="visualization..html#base-r-visualizations"><i class="fa fa-check"></i><b>3.1.1</b> Base R Visualizations</a></li>
<li class="chapter" data-level="3.1.2" data-path="visualization..html"><a href="visualization..html#visualization-techniques"><i class="fa fa-check"></i><b>3.1.2</b> Visualization Techniques</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="visualization..html"><a href="visualization..html#tidyverse-universe-visualizations"><i class="fa fa-check"></i><b>3.2</b> <code>Tidyverse</code> universe Visualizations</a></li>
<li class="chapter" data-level="3.3" data-path="visualization..html"><a href="visualization..html#simple-maps"><i class="fa fa-check"></i><b>3.3</b> Simple maps</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="visualization..html"><a href="visualization..html#other-maps"><i class="fa fa-check"></i><b>3.3.1</b> Other maps</a></li>
<li class="chapter" data-level="3.3.2" data-path="visualization..html"><a href="visualization..html#key-advantages-of-sf"><i class="fa fa-check"></i><b>3.3.2</b> <strong>Key Advantages of <code>sf</code>:</strong></a></li>
<li class="chapter" data-level="3.3.3" data-path="visualization..html"><a href="visualization..html#useful-functions"><i class="fa fa-check"></i><b>3.3.3</b> <strong>Useful Functions</strong></a></li>
<li class="chapter" data-level="3.3.4" data-path="visualization..html"><a href="visualization..html#additional-resources"><i class="fa fa-check"></i><b>3.3.4</b> <strong>Additional Resources</strong></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="efficient-code.html"><a href="efficient-code.html"><i class="fa fa-check"></i><b>4</b> Efficient Code</a>
<ul>
<li class="chapter" data-level="4.1" data-path="efficient-code.html"><a href="efficient-code.html#equations"><i class="fa fa-check"></i><b>4.1</b> Equations</a></li>
<li class="chapter" data-level="4.2" data-path="efficient-code.html"><a href="efficient-code.html#callout-blocks"><i class="fa fa-check"></i><b>4.2</b> Callout blocks</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="reporting-and-sharing.html"><a href="reporting-and-sharing.html"><i class="fa fa-check"></i><b>5</b> Reporting and Sharing</a>
<ul>
<li class="chapter" data-level="5.1" data-path="reporting-and-sharing.html"><a href="reporting-and-sharing.html#publishing"><i class="fa fa-check"></i><b>5.1</b> Publishing</a></li>
<li class="chapter" data-level="5.2" data-path="reporting-and-sharing.html"><a href="reporting-and-sharing.html#pages"><i class="fa fa-check"></i><b>5.2</b> 404 pages</a></li>
<li class="chapter" data-level="5.3" data-path="reporting-and-sharing.html"><a href="reporting-and-sharing.html#metadata-for-sharing"><i class="fa fa-check"></i><b>5.3</b> Metadata for sharing</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references-1.html"><a href="references-1.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://mauromardones.github.io/Course_R_Statictics/" target="_blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R Basic Course</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="exploratory-data-analysis" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Section 2</span> Exploratory Data Analysis<a href="exploratory-data-analysis.html#exploratory-data-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Exploratory Data Analysis (EDA) is a crucial first step in analyzing data. It provides a summary of the main characteristics of datasets and helps identify patterns, outliers, and relationships.</p>
<p>This section demonstrates an exploratory data analysis (EDA) of the <strong>Palmer Penguins Dataset</strong> using both base R and Tidyverse. It includes cleaning, descriptive statistics, and relationships between variables.</p>
<div id="load-necessary-packages" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Load Necessary Packages<a href="exploratory-data-analysis.html#load-necessary-packages" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="exploratory-data-analysis.html#cb1-1" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">&quot;palmerpenguins&quot;</span>)) <span class="fu">install.packages</span>(<span class="st">&quot;palmerpenguins&quot;</span>)</span></code></pre></div>
<pre><code>## Loading required package: palmerpenguins</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="exploratory-data-analysis.html#cb3-1" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">&quot;tidyverse&quot;</span>)) <span class="fu">install.packages</span>(<span class="st">&quot;tidyverse&quot;</span>)</span></code></pre></div>
<pre><code>## Loading required package: tidyverse</code></pre>
<pre><code>## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
## ✔ dplyr     1.1.4     ✔ readr     2.1.5
## ✔ forcats   1.0.0     ✔ stringr   1.5.1
## ✔ ggplot2   3.5.1     ✔ tibble    3.2.1
## ✔ lubridate 1.9.3     ✔ tidyr     1.3.1
## ✔ purrr     1.0.2     
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()
## ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="exploratory-data-analysis.html#cb6-1" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb6-2"><a href="exploratory-data-analysis.html#cb6-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
</div>
<div id="load-and-clean-data" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Load and Clean Data<a href="exploratory-data-analysis.html#load-and-clean-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="exploratory-data-analysis.html#cb7-1" tabindex="-1"></a>penguins <span class="ot">&lt;-</span> palmerpenguins<span class="sc">::</span>penguins</span>
<span id="cb7-2"><a href="exploratory-data-analysis.html#cb7-2" tabindex="-1"></a>penguins_clean <span class="ot">&lt;-</span> <span class="fu">drop_na</span>(penguins)</span></code></pre></div>
</div>
<div id="basic-data-overview" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Basic Data Overview<a href="exploratory-data-analysis.html#basic-data-overview" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="exploratory-data-analysis.html#cb8-1" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">head</span>(penguins_clean))</span></code></pre></div>
<pre><code>## # A tibble: 6 × 8
##   species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
##   &lt;fct&gt;   &lt;fct&gt;              &lt;dbl&gt;         &lt;dbl&gt;             &lt;int&gt;       &lt;int&gt;
## 1 Adelie  Torgersen           39.1          18.7               181        3750
## 2 Adelie  Torgersen           39.5          17.4               186        3800
## 3 Adelie  Torgersen           40.3          18                 195        3250
## 4 Adelie  Torgersen           36.7          19.3               193        3450
## 5 Adelie  Torgersen           39.3          20.6               190        3650
## 6 Adelie  Torgersen           38.9          17.8               181        3625
## # ℹ 2 more variables: sex &lt;fct&gt;, year &lt;int&gt;</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="exploratory-data-analysis.html#cb10-1" tabindex="-1"></a><span class="fu">str</span>(penguins_clean)</span></code></pre></div>
<pre><code>## tibble [333 × 8] (S3: tbl_df/tbl/data.frame)
##  $ species          : Factor w/ 3 levels &quot;Adelie&quot;,&quot;Chinstrap&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ island           : Factor w/ 3 levels &quot;Biscoe&quot;,&quot;Dream&quot;,..: 3 3 3 3 3 3 3 3 3 3 ...
##  $ bill_length_mm   : num [1:333] 39.1 39.5 40.3 36.7 39.3 38.9 39.2 41.1 38.6 34.6 ...
##  $ bill_depth_mm    : num [1:333] 18.7 17.4 18 19.3 20.6 17.8 19.6 17.6 21.2 21.1 ...
##  $ flipper_length_mm: int [1:333] 181 186 195 193 190 181 195 182 191 198 ...
##  $ body_mass_g      : int [1:333] 3750 3800 3250 3450 3650 3625 4675 3200 3800 4400 ...
##  $ sex              : Factor w/ 2 levels &quot;female&quot;,&quot;male&quot;: 2 1 1 1 2 1 2 1 2 2 ...
##  $ year             : int [1:333] 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 ...</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="exploratory-data-analysis.html#cb12-1" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">select</span>(penguins_clean, <span class="fu">where</span>(is.numeric)))</span></code></pre></div>
<pre><code>##  bill_length_mm  bill_depth_mm   flipper_length_mm  body_mass_g  
##  Min.   :32.10   Min.   :13.10   Min.   :172       Min.   :2700  
##  1st Qu.:39.50   1st Qu.:15.60   1st Qu.:190       1st Qu.:3550  
##  Median :44.50   Median :17.30   Median :197       Median :4050  
##  Mean   :43.99   Mean   :17.16   Mean   :201       Mean   :4207  
##  3rd Qu.:48.60   3rd Qu.:18.70   3rd Qu.:213       3rd Qu.:4775  
##  Max.   :59.60   Max.   :21.50   Max.   :231       Max.   :6300  
##       year     
##  Min.   :2007  
##  1st Qu.:2007  
##  Median :2008  
##  Mean   :2008  
##  3rd Qu.:2009  
##  Max.   :2009</code></pre>
</div>
<div id="measures-of-central-tendency" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Measures of Central Tendency<a href="exploratory-data-analysis.html#measures-of-central-tendency" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="exploratory-data-analysis.html#cb14-1" tabindex="-1"></a>mean_flipper <span class="ot">&lt;-</span> <span class="fu">mean</span>(penguins_clean<span class="sc">$</span>flipper_length_mm)</span>
<span id="cb14-2"><a href="exploratory-data-analysis.html#cb14-2" tabindex="-1"></a>median_flipper <span class="ot">&lt;-</span> <span class="fu">median</span>(penguins_clean<span class="sc">$</span>flipper_length_mm)</span>
<span id="cb14-3"><a href="exploratory-data-analysis.html#cb14-3" tabindex="-1"></a>mean_flipper</span></code></pre></div>
<pre><code>## [1] 200.967</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="exploratory-data-analysis.html#cb16-1" tabindex="-1"></a>median_flipper</span></code></pre></div>
<pre><code>## [1] 197</code></pre>
</div>
<div id="measures-of-spread" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Measures of Spread<a href="exploratory-data-analysis.html#measures-of-spread" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="exploratory-data-analysis.html#cb18-1" tabindex="-1"></a>range_body_mass <span class="ot">&lt;-</span> <span class="fu">range</span>(penguins_clean<span class="sc">$</span>body_mass_g)</span>
<span id="cb18-2"><a href="exploratory-data-analysis.html#cb18-2" tabindex="-1"></a>var_body_mass <span class="ot">&lt;-</span> <span class="fu">var</span>(penguins_clean<span class="sc">$</span>body_mass_g)</span>
<span id="cb18-3"><a href="exploratory-data-analysis.html#cb18-3" tabindex="-1"></a>sd_body_mass <span class="ot">&lt;-</span> <span class="fu">sd</span>(penguins_clean<span class="sc">$</span>body_mass_g)</span></code></pre></div>
</div>
<div id="frequency-tables-for-categorical-data" class="section level2 hasAnchor" number="2.6">
<h2><span class="header-section-number">2.6</span> Frequency Tables for Categorical Data<a href="exploratory-data-analysis.html#frequency-tables-for-categorical-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="exploratory-data-analysis.html#cb19-1" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">table</span>(penguins_clean<span class="sc">$</span>species))</span></code></pre></div>
<pre><code>## 
##    Adelie Chinstrap    Gentoo 
##       146        68       119</code></pre>
</div>
<div id="relationships-between-variables" class="section level2 hasAnchor" number="2.7">
<h2><span class="header-section-number">2.7</span> Relationships Between Variables<a href="exploratory-data-analysis.html#relationships-between-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="exploratory-data-analysis.html#cb21-1" tabindex="-1"></a>cov_bill <span class="ot">&lt;-</span> <span class="fu">cov</span>(penguins_clean<span class="sc">$</span>bill_length_mm, penguins_clean<span class="sc">$</span>bill_depth_mm)</span>
<span id="cb21-2"><a href="exploratory-data-analysis.html#cb21-2" tabindex="-1"></a>cor_bill <span class="ot">&lt;-</span> <span class="fu">cor</span>(penguins_clean<span class="sc">$</span>bill_length_mm, penguins_clean<span class="sc">$</span>bill_depth_mm)</span></code></pre></div>
</div>
<div id="outlier-detection" class="section level2 hasAnchor" number="2.8">
<h2><span class="header-section-number">2.8</span> Outlier Detection<a href="exploratory-data-analysis.html#outlier-detection" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="exploratory-data-analysis.html#cb22-1" tabindex="-1"></a>q1 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(penguins_clean<span class="sc">$</span>body_mass_g, <span class="fl">0.25</span>)</span>
<span id="cb22-2"><a href="exploratory-data-analysis.html#cb22-2" tabindex="-1"></a>q3 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(penguins_clean<span class="sc">$</span>body_mass_g, <span class="fl">0.75</span>)</span>
<span id="cb22-3"><a href="exploratory-data-analysis.html#cb22-3" tabindex="-1"></a>iqr_value <span class="ot">&lt;-</span> q3 <span class="sc">-</span> q1</span>
<span id="cb22-4"><a href="exploratory-data-analysis.html#cb22-4" tabindex="-1"></a>lower_bound <span class="ot">&lt;-</span> q1 <span class="sc">-</span> <span class="fl">1.5</span> <span class="sc">*</span> iqr_value</span>
<span id="cb22-5"><a href="exploratory-data-analysis.html#cb22-5" tabindex="-1"></a>upper_bound <span class="ot">&lt;-</span> q3 <span class="sc">+</span> <span class="fl">1.5</span> <span class="sc">*</span> iqr_value</span>
<span id="cb22-6"><a href="exploratory-data-analysis.html#cb22-6" tabindex="-1"></a></span>
<span id="cb22-7"><a href="exploratory-data-analysis.html#cb22-7" tabindex="-1"></a>outliers <span class="ot">&lt;-</span> penguins_clean <span class="sc">%&gt;%</span> </span>
<span id="cb22-8"><a href="exploratory-data-analysis.html#cb22-8" tabindex="-1"></a>  <span class="fu">filter</span>(body_mass_g <span class="sc">&lt;</span> lower_bound <span class="sc">|</span> body_mass_g <span class="sc">&gt;</span> upper_bound) <span class="sc">%&gt;%</span> </span>
<span id="cb22-9"><a href="exploratory-data-analysis.html#cb22-9" tabindex="-1"></a>  <span class="fu">select</span>(species, body_mass_g)</span>
<span id="cb22-10"><a href="exploratory-data-analysis.html#cb22-10" tabindex="-1"></a></span>
<span id="cb22-11"><a href="exploratory-data-analysis.html#cb22-11" tabindex="-1"></a><span class="fu">print</span>(outliers)</span></code></pre></div>
<pre><code>## # A tibble: 0 × 2
## # ℹ 2 variables: species &lt;fct&gt;, body_mass_g &lt;int&gt;</code></pre>
</div>
<div id="comparison-between-groups" class="section level2 hasAnchor" number="2.9">
<h2><span class="header-section-number">2.9</span> Comparison Between Groups<a href="exploratory-data-analysis.html#comparison-between-groups" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="exploratory-data-analysis.html#cb24-1" tabindex="-1"></a>penguins_clean <span class="sc">%&gt;%</span> </span>
<span id="cb24-2"><a href="exploratory-data-analysis.html#cb24-2" tabindex="-1"></a>  <span class="fu">filter</span>(species <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Adelie&quot;</span>, <span class="st">&quot;Gentoo&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="exploratory-data-analysis.html#cb24-3" tabindex="-1"></a>  <span class="fu">group_by</span>(species) <span class="sc">%&gt;%</span></span>
<span id="cb24-4"><a href="exploratory-data-analysis.html#cb24-4" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb24-5"><a href="exploratory-data-analysis.html#cb24-5" tabindex="-1"></a>    <span class="at">mean_body_mass =</span> <span class="fu">mean</span>(body_mass_g),</span>
<span id="cb24-6"><a href="exploratory-data-analysis.html#cb24-6" tabindex="-1"></a>    <span class="at">sd_body_mass =</span> <span class="fu">sd</span>(body_mass_g)</span>
<span id="cb24-7"><a href="exploratory-data-analysis.html#cb24-7" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 2 × 3
##   species mean_body_mass sd_body_mass
##   &lt;fct&gt;            &lt;dbl&gt;        &lt;dbl&gt;
## 1 Adelie           3706.         459.
## 2 Gentoo           5092.         501.</code></pre>
</div>
<div id="statistical-test-t-test" class="section level2 hasAnchor" number="2.10">
<h2><span class="header-section-number">2.10</span> Statistical Test: t-Test<a href="exploratory-data-analysis.html#statistical-test-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="exploratory-data-analysis.html#cb26-1" tabindex="-1"></a>penguins_subset <span class="ot">&lt;-</span> penguins_clean <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="exploratory-data-analysis.html#cb26-2" tabindex="-1"></a>  <span class="fu">filter</span>(species <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Adelie&quot;</span>, <span class="st">&quot;Gentoo&quot;</span>))</span>
<span id="cb26-3"><a href="exploratory-data-analysis.html#cb26-3" tabindex="-1"></a></span>
<span id="cb26-4"><a href="exploratory-data-analysis.html#cb26-4" tabindex="-1"></a>t_test_result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(body_mass_g <span class="sc">~</span> species, </span>
<span id="cb26-5"><a href="exploratory-data-analysis.html#cb26-5" tabindex="-1"></a>                        <span class="at">data =</span> penguins_subset)</span>
<span id="cb26-6"><a href="exploratory-data-analysis.html#cb26-6" tabindex="-1"></a></span>
<span id="cb26-7"><a href="exploratory-data-analysis.html#cb26-7" tabindex="-1"></a></span>
<span id="cb26-8"><a href="exploratory-data-analysis.html#cb26-8" tabindex="-1"></a><span class="fu">print</span>(t_test_result)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  body_mass_g by species
## t = -23.254, df = 242.14, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means between group Adelie and group Gentoo is not equal to 0
## 95 percent confidence interval:
##  -1503.702 -1268.843
## sample estimates:
## mean in group Adelie mean in group Gentoo 
##             3706.164             5092.437</code></pre>
<p>The null hypothesis (<code>H0</code>) assumes that the mean body mass of <em>Adelie</em> and <em>Gentoo</em> penguins is the same. If the p-value &lt; 0.05, we reject <code>H0</code>, indicating a significant difference in the body mass of these species.</p>
<p>p-value: If <code>p &lt; 0.05</code>, we reject H0, indicating a significant difference in the body mass of these species.</p>
<p>Confidence interval: Provides the range within which the true difference in means lies.</p>
<p>t-statistic: Indicates the magnitude of the difference relative to variability.</p>
</div>
<div id="one-way-anova" class="section level2 hasAnchor" number="2.11">
<h2><span class="header-section-number">2.11</span> One-Way ANOVA<a href="exploratory-data-analysis.html#one-way-anova" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="exploratory-data-analysis.html#cb28-1" tabindex="-1"></a>anova_body_mass <span class="ot">&lt;-</span> <span class="fu">aov</span>(bill_length_mm <span class="sc">~</span> species, <span class="at">data =</span> penguins_clean)</span>
<span id="cb28-2"><a href="exploratory-data-analysis.html#cb28-2" tabindex="-1"></a><span class="fu">summary</span>(anova_body_mass)</span></code></pre></div>
<pre><code>##              Df Sum Sq Mean Sq F value Pr(&gt;F)    
## species       2   7015    3508   397.3 &lt;2e-16 ***
## Residuals   330   2914       9                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="simple-linear-regression" class="section level2 hasAnchor" number="2.12">
<h2><span class="header-section-number">2.12</span> Simple Linear Regression<a href="exploratory-data-analysis.html#simple-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="exploratory-data-analysis.html#cb30-1" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_mass_g <span class="sc">~</span> flipper_length_mm, <span class="at">data =</span> penguins_clean)</span>
<span id="cb30-2"><a href="exploratory-data-analysis.html#cb30-2" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = body_mass_g ~ flipper_length_mm, data = penguins_clean)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1057.33  -259.79   -12.24   242.97  1293.89 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       -5872.09     310.29  -18.93   &lt;2e-16 ***
## flipper_length_mm    50.15       1.54   32.56   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 393.3 on 331 degrees of freedom
## Multiple R-squared:  0.7621, Adjusted R-squared:  0.7614 
## F-statistic:  1060 on 1 and 331 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Interpretation:</p>
<p><code>lm(formula = body_mass_g ~ flipper_length_mm, data = penguins_clean)</code></p>
<p>This indicates that the <strong>body mass</strong> (dependent variable) is being modeled as a function of
<strong>flipper length</strong> (independent variable) using the <code>lm()</code> function.</p>
<p><strong>2. Residuals:</strong></p>
<p>Min 1Q Median 3Q Max
-1057.33 -259.79 -12.24 242.97 1293.89</p>
<ul>
<li><strong>Residuals</strong> represent the differences between the observed values (body mass)
and the predicted values from the regression model.</li>
<li>The residuals range from -1057.33 to 1293.89.</li>
<li><strong>1st Quartile (1Q)</strong>: -259.79 (lower bound of the data distribution).</li>
<li><strong>Median</strong>: -12.24 (the middle value).</li>
<li><strong>3rd Quartile (3Q)</strong>: 242.97 (upper bound of the data distribution).</li>
<li><strong>Max</strong>: 1293.89 (the largest residual).</li>
</ul>
<p>Ideally, residuals should be evenly distributed around 0 for a good model fit.
The spread of residuals suggests some variance, but there’s no major sign of non-linearity in this output.</p>
<p><strong>3. Coefficients:</strong></p>
<p>Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) -5872.09 310.29 -18.93 &lt;2e-16 <strong><em>
flipper_length_mm 50.15 1.54 32.56 &lt;2e-16 </em></strong></p>
<ul>
<li><p><strong>Intercept</strong>: -5872.09</p></li>
<li><p>This is the estimated value of <strong>body mass</strong> when <strong>flipper length</strong> is 0 mm.
In a real-world context, this intercept doesn’t make sense because a flipper length of 0
mm is unrealistic. It’s just a mathematical value.</p></li>
<li><p><strong>Flipper_length_mm coefficient</strong>: 50.15</p></li>
<li><p>For every 1 mm increase in <strong>flipper length</strong>, <strong>body mass</strong> increases by
approximately <strong>50.15 grams</strong>. This is the <strong>slope</strong> of the regression line.</p></li>
<li><p><strong>Standard Error</strong>: 310.29 (intercept) and 1.54 (flipper length coefficient)</p></li>
<li><p>This measures the accuracy of the coefficient estimates.
Smaller values indicate more precise estimates.</p></li>
<li><p><strong>t-value</strong>: -18.93 (Intercept) and 32.56 (flipper length coefficient)</p></li>
<li><p>The t-value tests the hypothesis that the coefficient is significantly different from zero.
The larger the t-value, the stronger the evidence against the null hypothesis.</p></li>
<li><p><strong>Pr(&gt;|t|)</strong>: &lt; 2e-16 (both coefficients)</p></li>
<li><p>This is the <strong>p-value</strong> for each coefficient. A value below <strong>0.05</strong>
indicates statistical significance, meaning there’s strong evidence that
the coefficient is not equal to zero. Here, both the intercept and the slope are
<strong>highly significant</strong> with p-values much smaller than 0.05.</p></li>
</ul>
<p><strong>4. Model Summary:</strong></p>
<p>Residual standard error: 393.3 on 331 degrees of freedom
Multiple R-squared: 0.7621, Adjusted R-squared: 0.7614
F-statistic: 1060 on 1 and 331 DF, p-value: &lt; 2.2e-16</p>
<p><strong>Residual Standard Error</strong>: 393.3</p>
<ul>
<li>This is the average distance that the observed values deviate from the
regression line. A lower value indicates a better fit, although this needs to
be interpreted relative to the scale of <strong>body mass</strong>.</li>
</ul>
<p><strong>Multiple R-squared</strong>: 0.7621
- This indicates that about <strong>76.21%</strong> of the variability in <strong>body mass</strong>
can be explained by the <strong>flipper length</strong>. A value closer to 1 suggests a better fit of the model.</p>
<p><strong>Adjusted R-squared</strong>: 0.7614
- This is similar to R-squared but adjusts for the number of predictors in the model.
It is used to assess the model’s fit when there are multiple predictors,
although in this case, we have only one predictor.</p>
<p><strong>F-statistic</strong>: 1060 on 1 and 331 degrees of freedom, p-value: &lt; 2.2e-16
- The <strong>F-statistic</strong> tests whether at least one predictor variable has a
non-zero coefficient (i.e., the model is a good fit). Here, the F-statistic is very large,
and the p-value is extremely small, indicating that the model explains the data well.</p>
<p><strong>Interpretation:</strong></p>
<ul>
<li><strong>Relationship</strong>: There is a <strong>strong, positive relationship</strong> between <strong>flipper length</strong> and <strong>body mass</strong>. As flipper length increases by 1 mm, <strong>body mass</strong> increases by approximately <strong>50.15 grams</strong>.</li>
<li><strong>Model Fit</strong>: The <strong>Multiple R-squared value</strong> (0.7621) suggests that the model explains about 76% of the variance in <strong>body mass</strong> based on <strong>flipper length</strong>.</li>
<li><strong>Significance</strong>: Both the intercept and the slope are highly significant, with <strong>p-values</strong> near <strong>0</strong> (less than 0.05), suggesting that the relationship between <strong>flipper length</strong> and <strong>body mass</strong> is statistically significant.</li>
<li><strong>Error</strong>: The <strong>residual standard error</strong> of 393.3 suggests that the predictions of body mass from this model could be off by around 393 grams on average. This might be large compared to the range of body masses (which is typically less than 10000 grams), so there might still be other factors affecting <strong>body mass</strong>.</li>
</ul>
</div>
<div id="multiple-regresion" class="section level2 hasAnchor" number="2.13">
<h2><span class="header-section-number">2.13</span> Multiple Regresion<a href="exploratory-data-analysis.html#multiple-regresion" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="exploratory-data-analysis.html#cb32-1" tabindex="-1"></a>model_multiple <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_mass_g <span class="sc">~</span> flipper_length_mm <span class="sc">+</span> </span>
<span id="cb32-2"><a href="exploratory-data-analysis.html#cb32-2" tabindex="-1"></a>                       bill_length_mm <span class="sc">+</span> </span>
<span id="cb32-3"><a href="exploratory-data-analysis.html#cb32-3" tabindex="-1"></a>                       bill_depth_mm, </span>
<span id="cb32-4"><a href="exploratory-data-analysis.html#cb32-4" tabindex="-1"></a>                     <span class="at">data =</span> penguins_clean)</span>
<span id="cb32-5"><a href="exploratory-data-analysis.html#cb32-5" tabindex="-1"></a><span class="fu">summary</span>(model_multiple)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = body_mass_g ~ flipper_length_mm + bill_length_mm + 
##     bill_depth_mm, data = penguins_clean)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1051.37  -284.50   -20.37   241.03  1283.51 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       -6445.476    566.130 -11.385   &lt;2e-16 ***
## flipper_length_mm    50.762      2.497  20.327   &lt;2e-16 ***
## bill_length_mm        3.293      5.366   0.614    0.540    
## bill_depth_mm        17.836     13.826   1.290    0.198    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 393 on 329 degrees of freedom
## Multiple R-squared:  0.7639, Adjusted R-squared:  0.7618 
## F-statistic: 354.9 on 3 and 329 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Interpretation</p>
<pre><code>**Model Overview:**</code></pre>
<p>The model you ran predicts <code>body_mass_g</code> (body mass of penguins) based on three predictors:
1. <code>flipper_length_mm</code> (flipper length in mm),
2. <code>bill_length_mm</code> (bill length in mm),
3. <code>bill_depth_mm</code> (bill depth in mm).</p>
<p><strong>1. Residuals:</strong>
The residuals represent the differences between the observed and predicted values for the <code>body_mass_g</code>. The values provided are:</p>
<ul>
<li><strong>Min:</strong> -1051.37 (the smallest residual),</li>
<li><strong>1st Quartile (1Q):</strong> -284.50 (25th percentile of residuals),</li>
<li><strong>Median:</strong> -20.37 (50th percentile of residuals),</li>
<li><strong>3rd Quartile (3Q):</strong> 241.03 (75th percentile of residuals),</li>
<li><strong>Max:</strong> 1283.51 (the largest residual).</li>
</ul>
<p>These values suggest that the residuals are somewhat spread out,
with the median being close to zero, which is expected. The range of residuals shows some
relatively large errors, particularly on the high side (positive residuals).</p>
<p><strong>2. Coefficients:</strong>
The coefficients represent the estimated effect of each predictor variable on the outcome
(<code>body_mass_g</code>). Here’s a breakdown of each coefficient:</p>
<ul>
<li><p><strong>Intercept:</strong> -6445.476</p></li>
<li><p>This is the estimated body mass when all predictor variables (flipper length, bill length, and bill depth)
are zero. In practice, the intercept may not always have a meaningful interpretation but is necessary
for the linear model calculation.</p></li>
<li><p><strong>Flipper length (<code>flipper_length_mm</code>):</strong> 50.762</p></li>
<li><p>For every 1 mm increase in <code>flipper_length_mm</code>, the body mass (<code>body_mass_g</code>)
increases by approximately 50.76 grams. This predictor is highly significant with a very low p-value (<code>&lt; 2e-16</code>),
indicating a strong relationship with body mass.</p></li>
<li><p><strong>Bill length (<code>bill_length_mm</code>):</strong> 3.293</p></li>
<li><p>For every 1 mm increase in <code>bill_length_mm</code>, the body mass (<code>body_mass_g</code>)
increases by approximately 3.29 grams. However, the p-value for this coefficient is 0.540,
which is <strong>not statistically significant</strong> (p-value &gt; 0.05). This means bill length is
not a strong predictor of body mass in this model.</p></li>
<li><p><strong>Bill depth (<code>bill_depth_mm</code>):</strong> 17.836</p></li>
<li><p>For every 1 mm increase in <code>bill_depth_mm</code>, the body mass (<code>body_mass_g</code>) increases
by approximately 17.84 grams. However, the p-value for this coefficient is 0.198,
which is <strong>also not statistically significant</strong> (p-value &gt; 0.05). Bill depth does not
significantly contribute to predicting body mass in this model.</p></li>
</ul>
<p><strong>3. Residual Standard Error:</strong>
- The <strong>residual standard error</strong> (393) is the average amount by which the model’s predictions differ from the actual observed values. It gives a measure of how well the model fits the data. A smaller value is better, and 393 suggests that the model has moderate prediction error.</p>
<p><strong>4. R-squared and Adjusted R-squared:</strong>
- <strong>Multiple R-squared:</strong> 0.7639
- This means that about 76.4% of the variability in body mass (<code>body_mass_g</code>) can be explained by the three predictor variables (flipper length, bill length, and bill depth). This is a relatively high proportion of variance explained, indicating a good fit.</p>
<ul>
<li><strong>Adjusted R-squared:</strong> 0.7618
<ul>
<li>This value is adjusted for the number of predictors in the model, and it’s very close to the R-squared value, indicating that the inclusion of the predictors is adding value to the model and not overfitting.</li>
</ul></li>
</ul>
<p><strong>5. F-statistic:</strong>
- The <strong>F-statistic</strong> (354.9) tests whether the model as a whole is significant (i.e., whether the predictors are jointly useful for predicting body mass). The associated <strong>p-value</strong> (<code>&lt; 2.2e-16</code>) is extremely small, meaning that at least one of the predictors is significantly related to the outcome variable. In other words, the model is highly significant.</p>
<p><strong>Summary:</strong></p>
<ul>
<li><strong>Flipper length (<code>flipper_length_mm</code>)</strong> is the most important predictor of penguin body mass, with a statistically significant relationship.</li>
<li><strong>Bill length</strong> and <strong>bill depth</strong> are not significant predictors in this model, as their p-values are much higher than 0.05.</li>
<li>The model explains a high percentage (76.4%) of the variability in body mass.</li>
<li>The overall model is statistically significant, with a very low p-value for the F-statistic.</li>
</ul>
<p>This model can be useful for predicting penguin body mass based on flipper length, but the inclusion of bill length and bill depth does not add much value for this specific outcome.</p>
</div>
<div id="conclusion-1" class="section level2 hasAnchor" number="2.14">
<h2><span class="header-section-number">2.14</span> Conclusion<a href="exploratory-data-analysis.html#conclusion-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This script demonstrates exploratory data analysis (EDA) using both Base R and Tidyverse, including cleaning, descriptive statistics, and relationships between variables. The statistical tests (t-test and ANOVA) provide insights into differences between groups, while regression analysis highlights potential predictive relationships.</p>
</div>
<div id="final-thoughts" class="section level2 hasAnchor" number="2.15">
<h2><span class="header-section-number">2.15</span> Final Thoughts<a href="exploratory-data-analysis.html#final-thoughts" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>EDA is critical for understanding your data.<br />
</li>
<li>Data handling ensures clean datasets.<br />
</li>
<li>Data manipulation prepares data for in-depth analysis.<br />
</li>
<li>Visualization helps reveal insights quickly.</li>
</ul>
</div>
<div id="references" class="section level2 hasAnchor" number="2.16">
<h2><span class="header-section-number">2.16</span> References<a href="exploratory-data-analysis.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><a href="https://psyteachr.github.io/introdataviz/introduction.html">Basic R</a></p>
<p><a href="https://cran.r-project.org/web/packages/DataExplorer/vignettes/dataexplorer-intro.html">Data Explorer</a></p>
<p><a href="https://eda.seas.gwu.edu/2022-Fall/class/1-getting-started.html">EMSE 4572</a>
<a href="https://www.jumpingrivers.com/blog/best-practices-data-cleaning-r/">CleanData</a></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="user.-intro-to-r-and-basic-features.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="visualization..html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/mauromardones/Course_R_Statictics/main/02-EDA.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
},
"self_contained": false,
"output_dir": "docs",
"collapse_section": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
